var test = "Лёгкая";
var peremeshat_voprosi = "да";
var vopros_1 = "<font face = 'calibri'>Как зовут Ассасина?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_2 = "<font face = 'calibri'>Как зовут Бога Войны?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_3 = "<font face = 'calibri'>Какая компания создала серию игр Assasin's Creed?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_4 = "<font face = 'calibri'>В каком году вышла игра GTA V?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_5 = "<font face = 'calibri'>Какая игра стала 'Игрой Года' в 2021 году?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_6 = "<font face = 'calibri'>Какая компания создала игры 'The Last of us' и 'The Last of us 2'?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_7 = "<font face = 'calibri'>Сколько основных игр в серии 'Uncharted'?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_8 = "<font face = 'calibri'>Сколько игр в серии 'Assasins's Creed'?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_9 = "<font face = 'calibri'>Как зовут джеда?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_10 = "<font face = 'calibri'>Для скольких людей предназначена игра 'It takes two'?<br>(Варианты: Арно,Кел,Кратос)";
var vopros_11 = "<font face = 'calibri'>42*8 - 7 = <br>(Варианты: Арно,Кел,Кратос)";
var vopros_12 = "<font face = 'calibri'>43*6 - 5 = <br>(Варианты: Арно,Кел,Кратос)";
var vopros_13 = "<font face = 'calibri'>4*62 - 6 = <br>(Варианты: Арно,Кел,Кратос)";
var vopros_14 = "<font face = 'calibri'>45*9 - 9 = <br>(Варианты: Арно,Кел,Кратос)";
var vopros_15 = "<font face = 'calibri'>(Варианты: Арно,Кел,Кратос)<br>";
var vopros_ris_1 = "да";
var vopros_ris_2 = "нет";
var vopros_ris_3 = "нет";
var vopros_ris_4 = "да";
var vopros_ris_5 = "нет";
var vopros_ris_6 = "нет";
var vopros_ris_7 = "да";
var vopros_ris_8 = "нет";
var vopros_ris_9 = "нет";
var vopros_ris_10 = "нет";
var vopros_ris_11 = "нет";
var vopros_ris_12 = "нет";
var vopros_ris_13 = "нет";
var vopros_ris_14 = "нет";
var vopros_ris_15 = "да";
var pr_otv_zadachi_1 = "Q9g=="; 
var pr_otv_zadachi_2 = "Qw5B";
var pr_otv_zadachi_3 = "VWJpc29mdA==";
var pr_otv_zadachi_4 = "MjAxMw==";
var pr_otv_zadachi_5 = "SXQgdGFrZXMgdHdv";
var pr_otv_zadachi_6 = "TmF1Z2h0eSBEb2c=";
var pr_otv_zadachi_7 = "NA==";
var pr_otv_zadachi_8 = "MTI=";
var pr_otv_zadachi_9 = "U7";
var pr_otv_zadachi_10 = "Mg==";
var pr_otv_zadachi_11 = "MzI5";
var pr_otv_zadachi_12 = "MjUz";
var pr_otv_zadachi_13 = "MjQy";
var pr_otv_zadachi_14 = "Mzk2";
var pr_otv_zadachi_15 = "MzQy";